### ISSUE TITLE
Removing Reactions When Editing Reaction-Role Message

### ISSUE THREAD

**Issue by autumn-py** [Aninoss/lawliet-bot#46]
There's been times where I've had to change the emojis in a reaction-role message because of organisation and stuff. One thing I've noticed is when you edit the emojis for the message and re-send it, the old reactions are still there. I was just asking if you could possibly wipe all of the reactions of that message before adding the new reactions just so people don't have to constantly remove them manually. 
Thank you!
~ Violet

<img width="382" alt="Annotation 2022-06-08 101628" src="https://user-images.githubusercontent.com/83494967/172580220-2c79073f-d9fb-4e8e-bfe5-cd3e2882a371.png">

**Comment by Aninoss** [comment]
This should already be expected behaviour. It looks like it didn't work due to a JDA bug, a workaround has already been implemented and will be active in the next update
