### ISSUE TITLE
403 Forbbiden 

### ISSUE THREAD

**Issue by iiAngel** [Aninoss/lawliet-bot#58]
While testing NSFW commands and some links return "403 Forbbiden" 
![Screenshot_20230122-205945~2](https://user-images.githubusercontent.com/90804889/213958932-e0c53716-b392-4681-a096-497039d18f52.png)

**Comment by Aninoss** [comment]
Hello, could you please provide some links which return 403 as an example? Please make sure to include a NSFW warning just to be sure.

**Comment by iiAngel** [comment]
Oh yeah i've been investigating a bit and it's about NSFW videos the majority of them return "403 Forbidden"

(sorry for the delayed answer lol)

**Comment by Aninoss** [comment]
You still didn't mention any example as requested.
