### ISSUE TITLE
Bot Not Checking Content of Forwarded Messages

### ISSUE THREAD

**Issue by ephyrriz** [Aninoss/lawliet-bot#63]
Hello,

I hope you're doing well! I'd like to report a potential issue with the bot regarding **Discord's recently introduced "Forward Message" feature.**

A few months ago, Discord rolled out the "Forward Message" feature, and I believed that there might be some challenges with it, given it's a relatively new addition. After some testing a day ago, **I discovered that the bot doesn't seem to check the content of forwarded messages.** This **creates a loophole where users can bypass the bot's filters and send inappropriate content without triggering any checks.**

I'm unsure if this issue is already being addressed, but I wanted to bring it to your attention. This is a significant vulnerability, and I hope it can be resolved asap.

Thank you!

**Comment by ephyrriz** [comment]
Update: Might be an API version issue. I just checked the used for bot API version against the up-to-date one, and it seems you are behind by 2 versions. In version 5.12, the forward message feature appears to be mentioned, whereas in 5.10 it is not.

**Comment by Aninoss** [comment]
Hi, thanks for reaching out! I will work on a fix and probably deploy it in the next few days.

**Comment by ephyrriz** [comment]
Thanks you for the fix!
